export const authconstants = {
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_FAILURE : 'LOGIN_FAILURE',
    LOGOUT_REQUEST : 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE : 'LOGOUT_FAILURE'
}

export const userconstants = {
    USER_REGISTER_REQUEST : 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS : 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE : 'USER_REGISTER_FAILURE'
}

export const catconstants={
    GET_ALL_CATEGORY_REQUEST : 'GET_ALL_CATEGORY_REQUEST',
    GET_ALL_CATEGORY_SUCCESS : 'GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_FAILURE : 'GET_ALL_CATEGORY_FAILURE',
    ADD_NEW_CATEGORY_REQUEST : 'ADD_NEW_CATEGORY_REQUEST',
    ADD_NEW_CATEGORY_SUCCESS : 'ADD_NEW_CATEGORY_SUCCESS',
    ADD_NEW_CATEGORY_FAILURE : 'ADD_NEW_CATEGORY_FAILURE',
    UPDATE_CATEGORY_REQUEST : 'UPDATE_CATEGORY_REQUEST',
    UPDATE_CATEGORY_SUCCESS : 'UPDATE_CATEGORY_SUCCESS',
    UPDATE_CATEGORY_FAILURE : 'UPDATE_CATEGORY_FAILURE',
    DELETE_CATEGORY_REQUEST : 'DELETE_CATEGORY_REQUEST',
    DELETE_CATEGORY_SUCCESS : 'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_FAILURE : 'DELETE_CATEGORY_FAILURE'

}

export const intialDataconstants={
    GET_ALL_DATA_REQUEST : 'GET_ALL_DATA_REQUEST',
    GET_ALL_DATA_SUCCESS : 'GET_ALL_DATA_SUCCESS',
    GET_ALL_DATA_FAILURE : 'GET_ALL_DATA_FAILURE',
    // ADD_NEW_CATEGORY_REQUEST : 'ADD_NEW_CATEGORY_REQUEST',
    // ADD_NEW_CATEGORY_SUCCESS : 'ADD_NEW_CATEGORY_SUCCESS',
    // ADD_NEW_CATEGORY_FAILURE : 'ADD_NEW_CATEGORY_FAILURE'
}
export const productconstants={
    GET_ALL_PRODUCTS_REQUEST : 'GET_ALL_PRODUCTS_REQUEST',
    GET_ALL_PRODUCTS_SUCCESS : 'GET_ALL_PRODUCTS_SUCCESS',
    GET_ALL_PRODUCTS_FAILURE : 'GET_ALL_PRODUCTS_FAILURE',
    DELETE_PRODUCT_BY_ID_REQUEST: "DELETE_PRODUCT_BY_ID_REQUEST",
    DELETE_PRODUCT_BY_ID_SUCCESS: "DELETE_PRODUCT_BY_ID_SUCCESS",
    DELETE_PRODUCT_BY_ID_FAILURE: "DELETE_PRODUCT_BY_ID_FAILURE",
  
    ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
    ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_REQUEST",
    ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",
}

export const pageconstants={
    CREATE_PAGE_REQUEST : 'CREATE_PAGE_REQUEST',
    CREATE_PAGE_SUCCESS : 'CREATE_PAGE_SUCCESS',
    CREATE_PAGE_FAILURE : 'CREATE_PAGE_FAILURE'
}

export const orderConstants = {
    GET_CUSTOMER_ORDER_REQUEST: "GET_CUSTOMER_ORDER_REQUEST",
    GET_CUSTOMER_ORDER_SUCCESS: "GET_CUSTOMER_ORDER_SUCCESS",
    GET_CUSTOMER_ORDER_FAILURE: "GET_CUSTOMER_ORDER_FAILURE",
  
    UPDATE_CUSTOMER_ORDER_REQUEST: "UPDATE_CUSTOMER_ORDER_REQUEST",
    UPDATE_CUSTOMER_ORDER_SUCCESS: "UPDATE_CUSTOMER_ORDER_SUCCESS",
    UPDATE_CUSTOMER_ORDER_FAILURE: "UPDATE_CUSTOMER_ORDER_FAILURE",
  };
